name: university_attendance
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase: ^9.0.3
  firebase_core: ^3.10.1
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  shared_preferences: ^2.5.1
  google_fonts: ^4.0.4
  intl: ^0.19.0
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  flutter_svg: ^2.0.9
  gap: ^3.0.1
  firebase_storage: ^12.4.1
  image_picker: ^1.1.2
  meta: ^1.15.0
  smooth_page_indicator: ^1.2.0+3
  google_nav_bar: ^5.0.7
  url_launcher: ^6.3.1
  flutter_osm_plugin: ^1.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/onboard/
